spring.application.name=booking_ticket
server.port=8081
logging.level.org.springframework.security=DEBUG

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION_MS:86400000}
# config Hibernate (JPA)
# MySQL
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/quan-ly-ban-hang?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# C?u h\uFFFDnh danh s\uFFFDch c\uFFFDc node trong Cluster
#spring.redis.cluster.nodes=172.19.0.2:7001,172.19.0.6:7002,172.19.0.3:7003,172.19.0.5:7005,172.19.0.4:7006,172.19.0.5:7005
spring.redis.cluster.nodes=173.20.0.11:7001,173.20.0.12:7002,173.20.0.13:7003,173.20.0.14:7004,173.20.0.15:7005,173.20.0.16:7006

# C?u h\uFFFDnh Cache v\uFFFD Session (Gi? nguy\uFFFDn ho?c t\uFFFDy ch?nh)
spring.cache.type=redis
spring.session.store-type=redis
spring.session.timeout=30m
spring.redis.timeout=5000ms

# T\uFFFDy ch?n: C?u h\uFFFDnh th\uFFFDm cho Redis Client (Lettuce) ?? t? ??ng l\uFFFDm m?i s? ?? c?m
spring.redis.lettuce.cluster.refresh.adaptive=true
spring.redis.lettuce.cluster.refresh.period=60s

# Kafka cluster
spring.kafka.bootstrap-servers=localhost:9092,localhost:9093,localhost:9094

# Producer
spring.kafka.producer.acks=all
spring.kafka.producer.enable-idempotence=true
spring.kafka.producer.retries=3

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer
spring.kafka.listener.concurrency=3

# Disable auto topic creation
spring.kafka.admin.auto-create=false

#minio.url: http://localhost:9000
#minio.access-key=${MINIO_ACCESS_KEY:}
#minio.secret-key=${MINIO_SECRET_KEY:}
#minio.bucket: user-avatars
#
#spring.web.resources.static-locations: file:uploads/
